services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
    ports:
      - "5432:5432"
    networks:
      - backend-network

  backend:
    build: .
    command: npm run dev
    volumes:
      - .:/app:Z
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    networks:
      - backend-network

  sequelize:
    build: .
    command: npx sequelize-cli db:migrate
    volumes:
      - .:/app:Z
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    networks:
      - backend-network

volumes:
  pgdata:

networks:
  backend-network:
    driver: bridge
